### ISSUE TITLE
Información de interés

### ISSUE THREAD

**Issue by alu0100836059** [SistYTWnoeJacobo/TareasInicialesSYTW#1]
**Dejo aquí un par de páginas guía que me han parecido interesantes**:
- [Guía de markdown de git](https://guides.github.com/features/mastering-markdown/)
- [Guía acerca de la correcta creación de issues](https://guides.github.com/features/issues/)
- [Utilización de Wiki de Github](https://www.adictosaltrabajo.com/tutoriales/github-wiki/)

**Comment by alu0100622492** [comment]
Perfecto!.
